version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch
      - kibana
      - prometheus
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase?schema=public
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - PROMETHEUS_URL=http://prometheus:9090

  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.1"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.10.1"
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  prometheus:
    image: "prom/prometheus:latest"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis-data:
  rabbitmq-data:
  es-data:
  grafana-data:
